#!/usr/bin/env python3

TM_OFFSET   = 0x45A80C
TM_VAL_SIZE = 2
TM_TBL_SIZE = 50 * TM_VAL_SIZE
HM_OFFSET = TM_TBL_SIZE + TM_OFFSET_RED

TM_ORIGINAL = "0801510160015b012e005c00020153014b01ed00\
               f1000d013a003b003f007100b600f000ca00db00\
               da004c00e700550057005900d8005b005e00f700\
               1801680073005f013500bc00c9007e003d014c01\
               0301070122019c00d500a800d3001d0121013b01"

HM_ORIGINAL = "0f001300390046009400f9007f00"

MOVE_INDEX = [
    'Pound',
    'Karate_Chop',
    'Double_Slap',
    'Comet_Punch',
    'Mega_Punch',
    'Pay_Day',
    'Fire_Punch',
    'Ice_Punch',
    'Thunder_Punch',
    'Scratch',
    'Vice_Grip',
    'Guillotine',
    'Razor_Wind',
    'Swords_Dance',
    'Cut',
    'Gust',
    'Wing_Attack',
    'Whirlwind',
    'Fly',
    'Bind',
    'Slam',
    'Vine_Whip',
    'Stomp',
    'Double_Kick',
    'Mega_Kick',
    'Jump_Kick',
    'Rolling_Kick',
    'Sand_Attack',
    'Headbutt',
    'Horn_Attack',
    'Fury_Attack',
    'Horn_Drill',
    'Tackle',
    'Body_Slam',
    'Wrap',
    'Take_Down',
    'Thrash',
    'Double-Edge',
    'Tail_Whip',
    'Poison_Sting',
    'Twineedle',
    'Pin_Missile',
    'Leer',
    'Bite',
    'Growl',
    'Roar',
    'Sing',
    'Supersonic',
    'Sonic_Boom',
    'Disable',
    'Acid',
    'Ember',
    'Flamethrower',
    'Mist',
    'Water_Gun',
    'Hydro_Pump',
    'Surf',
    'Ice_Beam',
    'Blizzard',
    'Psybeam',
    'Bubble_Beam',
    'Aurora_Beam',
    'Hyper_Beam',
    'Peck',
    'Drill_Peck',
    'Submission',
    'Low_Kick',
    'Counter',
    'Seismic_Toss',
    'Strength',
    'Absorb',
    'Mega_Drain',
    'Leech_Seed',
    'Growth',
    'Razor_Leaf',
    'Solar_Beam',
    'Poison_Powder',
    'Stun_Spore',
    'Sleep_Powder',
    'Petal_Dance',
    'String_Shot',
    'Dragon_Rage',
    'Fire_Spin',
    'Thunder_Shock',
    'Thunderbolt',
    'Thunder_Wave',
    'Thunder',
    'Rock_Throw',
    'Earthquake',
    'Fissure',
    'Dig',
    'Toxic',
    'Confusion',
    'Psychic',
    'Hypnosis',
    'Meditate',
    'Agility',
    'Quick_Attack',
    'Rage',
    'Teleport',
    'Night_Shade',
    'Mimic',
    'Screech',
    'Double_Team',
    'Recover',
    'Harden',
    'Minimize',
    'Smokescreen',
    'Confuse_Ray',
    'Withdraw',
    'Defense_Curl',
    'Barrier',
    'Light_Screen',
    'Haze',
    'Reflect',
    'Focus_Energy',
    'Bide',
    'Metronome',
    'Mirror_Move',
    'Self-Destruct',
    'Egg_Bomb',
    'Lick',
    'Smog',
    'Sludge',
    'Bone_Club',
    'Fire_Blast',
    'Waterfall',
    'Clamp',
    'Swift',
    'Skull_Bash',
    'Spike_Cannon',
    'Constrict',
    'Amnesia',
    'Kinesis',
    'Soft-Boiled',
    'High_Jump_Kick',
    'Glare',
    'Dream_Eater',
    'Poison_Gas',
    'Barrage',
    'Leech_Life',
    'Lovely_Kiss',
    'Sky_Attack',
    'Transform',
    'Bubble',
    'Dizzy_Punch',
    'Spore',
    'Flash',
    'Psywave',
    'Splash',
    'Acid_Armor',
    'Crabhammer',
    'Explosion',
    'Fury_Swipes',
    'Bonemerang',
    'Rest',
    'Rock_Slide',
    'Hyper_Fang',
    'Sharpen',
    'Conversion',
    'Tri_Attack',
    'Super_Fang',
    'Slash',
    'Substitute',
    'Struggle',
    'Sketch',
    'Triple_Kick',
    'Thief',
    'Spider_Web',
    'Mind_Reader',
    'Nightmare',
    'Flame_Wheel',
    'Snore',
    'Curse',
    'Flail',
    'Conversion_2',
    'Aeroblast',
    'Cotton_Spore',
    'Reversal',
    'Spite',
    'Powder_Snow',
    'Protect',
    'Mach_Punch',
    'Scary_Face',
    'Feint_Attack',
    'Sweet_Kiss',
    'Belly_Drum',
    'Sludge_Bomb',
    'Mud-Slap',
    'Octazooka',
    'Spikes',
    'Zap_Cannon',
    'Foresight',
    'Destiny_Bond',
    'Perish_Song',
    'Icy_Wind',
    'Detect',
    'Bone_Rush',
    'Lock-On',
    'Outrage',
    'Sandstorm',
    'Giga_Drain',
    'Endure',
    'Charm',
    'Rollout',
    'False_Swipe',
    'Swagger',
    'Milk_Drink',
    'Spark',
    'Fury_Cutter',
    'Steel_Wing',
    'Mean_Look',
    'Attract',
    'Sleep_Talk',
    'Heal_Bell',
    'Return',
    'Present',
    'Frustration',
    'Safeguard',
    'Pain_Split',
    'Sacred_Fire',
    'Magnitude',
    'Dynamic_Punch',
    'Megahorn',
    'Dragon_Breath',
    'Baton_Pass',
    'Encore',
    'Pursuit',
    'Rapid_Spin',
    'Sweet_Scent',
    'Iron_Tail',
    'Metal_Claw',
    'Vital_Throw',
    'Morning_Sun',
    'Synthesis',
    'Moonlight',
    'Hidden_Power',
    'Cross_Chop',
    'Twister',
    'Rain_Dance',
    'Sunny_Day',
    'Crunch',
    'Mirror_Coat',
    'Psych_Up',
    'Extreme_Speed',
    'Ancient_Power',
    'Shadow_Ball',
    'Future_Sight',
    'Rock_Smash',
    'Whirlpool',
    'Beat_Up',
    'Fake_Out',
    'Uproar',
    'Stockpile',
    'Spit_Up',
    'Swallow',
    'Heat_Wave',
    'Hail',
    'Torment',
    'Flatter',
    'Will-O-Wisp',
    'Memento',
    'Facade',
    'Focus_Punch',
    'Smelling_Salts',
    'Follow_Me',
    'Nature_Power',
    'Charge',
    'Taunt',
    'Helping_Hand',
    'Trick',
    'Role_Play',
    'Wish',
    'Assist',
    'Ingrain',
    'Superpower',
    'Magic_Coat',
    'Recycle',
    'Revenge',
    'Brick_Break',
    'Yawn',
    'Knock_Off',
    'Endeavor',
    'Eruption',
    'Skill_Swap',
    'Imprison',
    'Refresh',
    'Grudge',
    'Snatch',
    'Secret_Power',
    'Dive',
    'Arm_Thrust',
    'Camouflage',
    'Tail_Glow',
    'Luster_Purge',
    'Mist_Ball',
    'Feather_Dance',
    'Teeter_Dance',
    'Blaze_Kick',
    'Mud_Sport',
    'Ice_Ball',
    'Needle_Arm',
    'Slack_Off',
    'Hyper_Voice',
    'Poison_Fang',
    'Crush_Claw',
    'Blast_Burn',
    'Hydro_Cannon',
    'Meteor_Mash',
    'Astonish',
    'Weather_Ball',
    'Aromatherapy',
    'Fake_Tears',
    'Air_Cutter',
    'Overheat',
    'Odor_Sleuth',
    'Rock_Tomb',
    'Silver_Wind',
    'Metal_Sound',
    'Grass_Whistle',
    'Tickle',
    'Cosmic_Power',
    'Water_Spout',
    'Signal_Beam',
    'Shadow_Punch',
    'Extrasensory',
    'Sky_Uppercut',
    'Sand_Tomb',
    'Sheer_Cold',
    'Muddy_Water',
    'Bullet_Seed',
    'Aerial_Ace',
    'Icicle_Spear',
    'Iron_Defense',
    'Block',
    'Howl',
    'Dragon_Claw',
    'Frenzy_Plant',
    'Bulk_Up',
    'Bounce',
    'Mud_Shot',
    'Poison_Tail',
    'Covet',
    'Volt_Tackle',
    'Magical_Leaf',
    'Water_Sport',
    'Calm_Mind',
    'Leaf_Blade',
    'Dragon_Dance',
    'Rock_Blast',
    'Shock_Wave',
    'Water_Pulse',
    'Doom_Desire',
    'Psycho_Boost'
    ]

# TM TODO
# TODO figure out how to edit the text for the TMs
# TODO figure out how to edit pokemon that can learn the TM
# TODO Inspect TM table and report on modifications

def main():
    with open( 'exclude/Pokemon_Fire_Red.rom', 'rb' ) as fh:
        fh.seek(HM_OFFSET_RED)
        print( fh.read(14).hex() )
        fh.seek(TM_OFFSET_RED)
        print("TM")
        for i in range(50):
            val = fh.read(2).hex()
            string = val[2:] + val[:2]
            print(string + " " + str(i+1))
        print("HM")
        for i in range(7):
            val = fh.read(2).hex()
            string = val[2:] + val[:2]
            print(string + " " + str(i+1))

def validate_TM_table( fh ):
    fh.seek(TM_OFFSET_RED)
    if fh.read(TM_TBL_SIZE).hex() == TM_ORIGINAL_RED:
        return True
    return False

def validate_HM_table( fh ):
    fh.seek(HM_OFFSET_RED)
    if fh.read(HM_TBL_SIZE).hex() == HM_ORIGINAL_RED:
        return True
    return False

def restore_HM_table( fh ):
    fh.seek(HM_OFFSET_RED)
    for b in [HM_ORIGINAL_RED[i:i+2] for i in range(0, len(HM_ORIGINAL_RED), 2)]:
        fh.write(bytes.fromhex(b), byteorder='big')

def restore_TM_table( fh ):
    fh.seek(TM_OFFSET_RED)
    for b in [TM_ORIGINAL_RED[i:i+2] for i in range(0, len(TM_ORIGINAL_RED), 2)]:
        fh.write(bytes.fromhex(b), byteorder='big')

def move_from_index( index )
    return MOVE_INDEX[index+1]

if __name__ == "__main__":
    main()
